### ISSUE TITLE
PSoC 62 support

### ISSUE THREAD

**Issue by tomoveu** [cypresssemiconductorco/Cypress-Peripheral-Driver-Library-v3.0.1#1]
Hello,

I am looking into the possibility of using PSoC 62 for an upcoming project,, but I noticed this library has support only for 63. Considering that the PSoC 62 is also a dual-core MCU and very similar to 63, would there be support for PSoC 62 in the Cypress Peripheral Driver Library?

Would it be a matter of just changing headers with register mappings or there are some significant differences between the PSoC 63 and 62 besides the radio?

Side-topic:
_It has also made an impression that there is lack of any PSoC modules and SOM. Perhaps someone using the PSOC low-level library could be aware of such MCU modules being available after all_ :-)

Best Regards,
Dimi

**Comment by JimTrudeau** [comment]
Dimi, my apologies that no one dealt with this in a timely fashion. I'm working on that. :)

Four months later.... 
PSoC 62 is supported in the peripheral driver library. That is now available as a separate repository. 
https://github.com/cypresssemiconductorco/psoc6pdl
